Sentimen_Movie/sentimen_hotel/sentimen_hotel/administrator/urls.py
from django.urls import path, include
from . import views

app_name = 'administrator'

urlpatterns = [
    path('', views.index, name='index'),
    path('sentimen_analisis/', views.sentimen, name='sentimen'),
    path('tentang/', views.tentang, name='tentang'),
    path('hasil/', views.hasil, name='hasil'),
    path('fitur/', views.fitur, name='fitur'),
    path('klasifikasi/', views.klasifikasi, name='klasifikasi'),
    path('SVM/', views.SVM, name='SVM'),
    path('hasilsvm/', views.hasilsvm, name='hasilsvm'),
    path('SVMRBF/', views.SVMRBF, name='SVMRBF'),
    path('hasilsvmrbf/', views.hasilsvmrbf, name='hasilsvmrbf'),
    path('SVMRBFIG/', views.SVMRBFIG, name='SVMRBFIG'),
    # path('latih/', views.latih, name='latih'),
    # path('save/', views.savekonfigurasi, name='save_konfigurasi'),
    # path('recognize/', views.face_recognition, name='face_recognition'),

]

Sentimen_Movie/sentimen_hotel/sentimen_hotel/sentimen_hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
        path('login/', views.custom_login, name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),
        path('', views.custom_login, name='index'),
        path('administrator/', include('administrator.urls', namespace='administrator')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sentimen_Movie/sentimen_hotel/sentimen_hotel/administrator/models.py
from django.db import models

# Create your models here.

Sentimen_Movie/sentimen_hotel/sentimen_hotel/administrator/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import decorator_from_middleware
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.contrib import messages
import random
from operator import itemgetter
import zipfile
import os
from shutil import copyfile

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from time import time

import nltk
from nltk.tokenize import WordPunctTokenizer
from bs4 import BeautifulSoup
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.feature_selection import SelectKBest, mutual_info_classif
from sklearn.metrics import accuracy_score
from sklearn import model_selection
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics



import shutil

import time
import numpy as np
import csv




# Create your views here.

def get_stemmed_text(corpus):
    stemmer = PorterStemmer()
    return [' '.join([stemmer.stem(word) for word in review.split()]) for review in corpus]

def remove_stop_words(corpus, english_stop_words):
    removed_stop_words = []
    for review in corpus:
        removed_stop_words.append(
        ' '.join([word for word in review.split()
        if word not in english_stop_words])
        )
    return removed_stop_words







@login_required(login_url=settings.LOGIN_URL)
def index(request):
    return render(request, 'administrator/dashboard.html')

@login_required(login_url=settings.LOGIN_URL)
def tentang(request):
    return render(request, 'administrator/tentang.html')

@login_required(login_url=settings.LOGIN_URL)
def SVM(request):
    return render(request, 'administrator/SVM.html')

@login_required(login_url=settings.LOGIN_URL)
def SVMRBF(request):
    return render(request, 'administrator/SVMRBF.html')

@login_required(login_url=settings.LOGIN_URL)
def SVMRBFIG(request):
    return render(request, 'administrator/SVMRBFIG.html')

@login_required(login_url=settings.LOGIN_URL)
def sentimen(request):
    if request.method == 'POST':
        file = request.FILES['data']
        if default_storage.exists('dataset.csv'):
            default_storage.delete('dataset.csv')
        file_name = default_storage.save('dataset.csv', file)

        dataset = []
        data = pd.read_csv(default_storage.path('dataset.csv'))
        for x in range(len(data['Message'])):
            temp = []
            temp.append(data['Message'][x])
            temp.append(data['kelas'][x])
            # print(data['sentiment'][x])
            dataset.append(temp)
        # path = default_storage.save('dataset.csv', ContentFile(file.read()))
        messages.success(request,'Dataset berhasil diupload!')

        return render(request, 'administrator/sentimen.html',{'dataset': dataset})
    else:
        if default_storage.exists('dataset.csv'):
            dataset = []
            data = pd.read_csv(default_storage.path('dataset.csv'))
            print(data['kelas'])
            for x in range(len(data['Message'])):
                temp = []
                temp.append(data['Message'][x])
                temp.append(data['kelas'][x])
                # print(data['sentiment'][x])
                dataset.append(temp)

            # with open(default_storage.path('dataset.csv'), 'r') as data:
            #     reader = csv.reader(data)
            #     dataset = []
            #     for row in reader:
            #         dataset.append(row)
            # print(dataset)

        else:
            dataset = []
        # nama=[]
        # jumlah=[]
        # dataset=[]
        # if default_storage.exists('dataset'):
        #     for name in os.listdir(os.path.join(settings.BASE_DIR, 'media/dataset')):
        #         dataset.append([str(name),str(len(os.listdir(os.path.join(settings.BASE_DIR, 'media/dataset/'+name))))])
        # # print(dataset)
        return render(request, 'administrator/sentimen.html',{'dataset': dataset})



@login_required(login_url=settings.LOGIN_URL)
def hasil(request):
    if default_storage.exists('dataset.csv'):
        data = pd.read_csv(default_storage.path('dataset.csv'))
        tok = WordPunctTokenizer()
        pat1 = r'@[A-Za-z0-9]+'
        pat2 = r'https?://[A-Za-z0-9./]+'
        combined_pat = r'|'.join((pat1, pat2))
        def tweet_cleaner(Message):
            soup = BeautifulSoup(Message, 'lxml')
            souped = soup.get_text()
            stripped = re.sub(combined_pat, '', souped)
            try:
                clean = stripped.decode("utf-8-sig").replace(u"\ufffd", "?")
            except:
                clean = stripped
            letters_only = re.sub("[^a-zA-Z]", " ", clean)
            lower_case = letters_only.lower()
            # During the letters_only process two lines above, it has created unnecessay white spaces,
            # I will tokenize and join together to remove unneccessary white spaces
            words = tok.tokenize(lower_case)
            return (" ".join(words)).strip()
        testing = data.Message[:2000]
        test_result = []
        for t in testing:
            test_result.append(tweet_cleaner(t))
        # print(test_result)

        english_stop_words = stopwords.words('english')
        data_remove = remove_stop_words(test_result, english_stop_words)
        # data_remove[:2])

        stem_data = get_stemmed_text(data_remove)
        # stem_data[:2]
        # print(stem_data[:2])

        clean_df = pd.DataFrame(stem_data,columns=['Message'])
        clean_df['target'] = data.kelas
        if default_storage.exists('clean_review.csv'):
            default_storage.delete('clean_review.csv')
# clean_df.head()
        clean_df.to_csv(default_storage.path('clean_review.csv'), encoding='utf-8')

        return render(request, 'administrator/hasil.html',{'tokenize':test_result,'stopwords_removal':data_remove,'stemming':stem_data})
    else:
        messages.error(request,'Dataset belum diinputkan!')
        return redirect('/administrator/sentimen_analisis/')
        pass

@login_required(login_url=settings.LOGIN_URL)
def fitur(request):
    if default_storage.exists('clean_review.csv'):
        csv = default_storage.path('clean_review.csv')
        my_df = pd.read_csv(csv, index_col=0)
        my_df.head(2000)
        x = my_df.Message
        y = my_df.target
        seed = 2000
        # Using CountVectorizer to convert text into tokens/features
        Encoder = LabelEncoder()
        Trans_Y = Encoder.fit_transform(y)
        Tfidf_vect = TfidfVectorizer(max_features=5000, min_df=4, max_df=0.8)
        Tfidf_vect.fit(x)
        X_Tfidf = Tfidf_vect.transform(x)
        Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(X_Tfidf, Trans_Y, test_size=0.2, random_state=seed)
        ig = SelectKBest(score_func=mutual_info_classif, k=2100)
        X_new = ig.fit_transform(Train_X, Train_Y)
        feature_scores = [(item, score) for item, score in zip(Tfidf_vect.get_feature_names(), ig.scores_)]
        topk = sorted(feature_scores, key=lambda x: -x[1])[:-1]

        return render(request, 'administrator/fitur.html',{ 'topk': topk})
    else:
        messages.error(request, 'Dataset belum diinputkan!')
        return redirect('/administrator/sentimen_analisis/')
        pass

@login_required(login_url=settings.LOGIN_URL)
def klasifikasi(request):
    if request.method == 'GET':
        a = float(request.GET['num1'])
        b = float(request.GET['num2'])
        c = int(request.GET['num3'])
    if default_storage.exists('clean_review.csv'):
        csv = default_storage.path('clean_review.csv')
        my_df = pd.read_csv(csv, index_col=0)
        my_df.head(2000)
        x = my_df.Message
        y = my_df.target
        seed = 2000
        # Using CountVectorizer to convert text into tokens/features
        Encoder = LabelEncoder()
        Trans_Y = Encoder.fit_transform(y)
        Tfidf_vect = TfidfVectorizer(max_features=5000, min_df=4, max_df=0.8)
        Tfidf_vect.fit(x)
        X_Tfidf = Tfidf_vect.transform(x)
        Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(X_Tfidf, Trans_Y, test_size=0.2, random_state=seed)
        ig = SelectKBest(score_func=mutual_info_classif, k=c)
        X_new = ig.fit_transform(Train_X, Train_Y)
        # Classifier - Algorithm - SVM
        # fit the training dataset on the classifier
        Train_x, Test_x, Train_y, Test_y = model_selection.train_test_split(X_new, Train_Y, random_state=seed)
        SVM_RBF_ig = SVC(C=a, kernel='rbf', gamma=b)
        SVM_RBF_ig.fit(Train_x, Train_y)
        # predict the labels on validation dataset
        predictions_SVM_RBF_ig = SVM_RBF_ig.predict(Test_x)
        # Use accuracy_score function to get the accuracy
        hasil_ig = accuracy_score(predictions_SVM_RBF_ig, Test_y) * 100
        # Making the Confusion Matrix
        accuracy_ig = {}
        cm = metrics.confusion_matrix(Test_y, predictions_SVM_RBF_ig)
        accuracy_ig[SVM_RBF_ig] = [SVM_RBF_ig,
                             round(metrics.accuracy_score(Test_y, predictions_SVM_RBF_ig), 2),
                             cm[0][0],  # true_negative
                             cm[0][1],  # false_positive
                             cm[1][0],  # false_negative
                             cm[1][1],  # true_positive
                             ]

        return render(request, 'administrator/klasifikasi.html',{'akurasi_ig':hasil_ig, 'matrix_ig':accuracy_ig})

    else:
        messages.error(request,'Dataset belum diinputkan!')
        return redirect('/administrator/sentimen_analisis/')
        pass
@login_required(login_url=settings.LOGIN_URL)
def hasilsvm(request):
    if default_storage.exists('clean_review.csv'):
        csv = default_storage.path('clean_review.csv')

Sentimen_Movie/sentimen_hotel/sentimen_hotel/templates/administrator/SVM.html
{% extends "layouts/administrator.html" %}
{% load static %}

{% block SVM %}
active-sub
{% endblock %}

{% block title %}
Hasil | Klasifikasi Analisis Sentimen Movie Review
{% endblock %}

{% block css %}
<!--DataTables [ OPTIONAL ]-->
<link href="{% static 'plugins/datatables/media/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css' %}" rel="stylesheet">
<!--Animate.css [ OPTIONAL ]-->
<link href="{% static 'plugins/animate-css/animate.min.css' %}" rel="stylesheet">

  <link href="{% static "plugins/dropify/css/dropify.css" %}" type="text/css" rel="stylesheet" media="screen,projection">
{% endblock %}

{% block content %}
<div id="content-container">
    <div id="page-head">

<div class="pad-all text-center">
<h3>Klasifikasi Algoritma SVM</h3>
<p>KLASIFIKASI ANALISIS SENTIMEN MOVIE REVIEW DENGAN METODE SUPPORT VECTOR MACHINE</p>
</div>
        </div>


    <!--Page content-->
    <!--===================================================-->
    <div id="page-content">
    <div class="panel">
          <div class="panel-heading">
              <h3 class="panel-title">Process</h3>
          </div>
          <div class="panel-body demo-nifty-btn">
            <a  class="btn btn-lg btn-primary" href="{% url 'administrator:hasilsvm' %}">Klasifikasi</a>
            </div>
</div>
                 <div class="panel">
          <div class="panel-heading">
              <h3 class="panel-title">Result SVM</h3>
          </div>
          <div class="panel-body demo-nifty-btn">
            <table id="demo-dt-basic3" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Akurasi</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>0%</td>
                    </tr>
                </tbody>
            </table>
            </div>
</div>
<div class="panel">
          <div class="panel-heading">
              <h3 class="panel-title">Confusion Matrix SVM</h3>
          </div>
          <div class="panel-body demo-nifty-btn">
            <table id="demo-dt-basic4" class="table table-striped table-bordered" cellspacing="0" width="100%">
               <thead>
                    <tr>
                    <th>  </th>
                    <th> Predicted Neg </th>
                    <th> Predicted Pos </th>
                    </tr>
                </thead>
                <tbody>
                  <tr>
                    <td> <b>Actual Neg</b> </td>
                    <td> 0 </td>
                    <td> 0 </td>
                    </tr>
                    <tr>
                    <td> <b>Actual Pos</b> </td>
                    <td> 0 </td>
                   <td> 0 </td>
                   </tr>
                </tbody>
            </table>
            </div>
</div>



    <!--===================================================-->
    <!--End page content-->

</div>

<div id="demo-lg-modal" class="modal fade" tabindex="-1">
      <div class="modal-dialog modal-lg animated bounceIn">
          <div class="modal-content">
            <form class="formValidate2" id="formValidate2" name="form_tambah" method="post" action="{% url 'administrator:sentimen' %}" enctype="multipart/form-data">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                  <h4 class="modal-title" id="myLargeModalLabel">Import Dataset</h4>
              </div>
              <div class="modal-body">

                  {% csrf_token %}
                <div class="row section">
            <div class="col-sm-12">
                <p>Upload Dataset (Maximum file upload size 10MB).</p>
                <input type="file" name="data" class="dropify" data-show-remove="false" data-allowed-file-extensions="csv" data-max-file-size="10M" required />
                    </div>
            </div>


              </div>

              <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>

              </form>
          </div>
      </div>
  </div>
{% endblock %}

{% block js %}

 <!--DataTables [ OPTIONAL ]-->
 <script src="{% static 'plugins/datatables/media/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables/media/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>


 <!--DataTables Sample [ SAMPLE ]-->
<script type="text/javascript">

  // Tables-DataTables.js
  // ====================================================================
  // This file should not be included in your project.
  // This is just a sample how to initialize plugins or components.
  //
  // - ThemeOn.net -



  $(document).on('nifty.ready', function() {


      // DATA TABLES
      // =================================================================
      // Require Data Tables
      // -----------------------------------------------------------------
      // http://www.datatables.net/
      // =================================================================

      $.fn.DataTable.ext.pager.numbers_length = 5;


      // Basic Data Tables with responsive plugin
      // -----------------------------------------------------------------
      $('#demo-dt-basic').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );


      $('#demo-dt-basic2').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );


      $('#demo-dt-basic3').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );


      $('#demo-dt-basic4').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );

      $('#demo-dt-basic5').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );


      $('#demo-dt-basic6').dataTable( {
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      } );





      // Row selection (single row)
      // -----------------------------------------------------------------
      var rowSelection = $('#demo-dt-selection').DataTable({
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          }
      });

      $('#demo-dt-selection').on( 'click', 'tr', function () {
          if ( $(this).hasClass('selected') ) {
              $(this).removeClass('selected');
          }
          else {
              rowSelection.$('tr.selected').removeClass('selected');
              $(this).addClass('selected');
          }
      } );






      // Row selection and deletion (multiple rows)
      // -----------------------------------------------------------------
      var rowDeletion = $('#demo-dt-delete').DataTable({
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          },
          "dom": '<"toolbar">frtip'
      });
      $('#demo-custom-toolbar').appendTo($("div.toolbar"));

      $('#demo-dt-delete tbody').on( 'click', 'tr', function () {
          $(this).toggleClass('selected');
      } );

      $('#demo-dt-delete-btn').click( function () {
          rowDeletion.rows('.selected').remove().draw( false );
      } );






      // Add Row
      // -----------------------------------------------------------------
      var t = $('#demo-dt-addrow').DataTable({
          "responsive": true,
          "language": {
              "paginate": {
                "previous": '<i class="demo-psi-arrow-left"></i>',
                "next": '<i class="demo-psi-arrow-right"></i>'
              }
          },
          "dom": '<"newtoolbar">frtip'
      });
      $('#demo-custom-toolbar2').appendTo($("div.newtoolbar"));

      var randomInt = function(min,max){
          return Math.floor(Math.random()*(max-min+1)+min);
      }
      $('#demo-dt-addrow-btn').on( 'click', function () {
          t.row.add( [
              'Adam Doe',
              'New Row',
              'New Row',
              randomInt(1,100),
              '2015/10/15',
              '$' + randomInt(1,100) +',000'
          ] ).draw();
      } );


  });

</script>
 <!--Bootbox Modals [ OPTIONAL ]-->
<script src="{% static 'plugins/bootbox/bootbox.min.js' %}"></script>

<script type="text/javascript" src="{% static "plugins/dropify/js/dropify.js" %}"></script>

{% endblock %}

Sentimen_Movie/sentimen_hotel/sentimen_hotel/templates/administrator/dashboard.html
{% extends "layouts/administrator.html" %}
{% load static %}

{% block dashboard %}
active-sub
{% endblock %}

{% block title %}
Dashboard | Klasifikasi Analisis Sentimen Movie Review
{% endblock %}

{% block content %}
<div id="content-container">
    <div id="page-head">

<div class="pad-all text-center">
  <style type="text/css">
  #img-weli {
    text-align: center;
  }

  .img-weli {
    width: 80px;
    border-radius:10px;
  }
</style>
      <div id="img-weli"><img src="/assets/img/weli.png" alt="" title="" name="slide" class="img-weli"></div>
<h3>Klasifikasi Analisis Sentimen <em>Movie Review</em> Dengan Metode <em>Support Vector Machine</em></h3>
<h3>Menggunakan Kernel <em>Radial Basis Function</em> dan <em>Information Gain</em></h3>
</div>
        </div>


    <!--Page content-->
    <!--===================================================-->
    <div id="page-content">

      <div id="page-content">
    <div class="col-md-9">
        <div class="panel">
            <div class="panel-body">
              <h4 class="panel-title">
                <i class="demo-pli-information"></i>
                    Petunjuk Penggunaan</h4>
                <div id="demo-gen-faq1" class="mar-ver collapse in">
                1. Siapkan dataset review dengan format .csv yang terdiri dari dua kolom. Kolom pertama untuk review berikan nama "Message" dan kedua untuk sentimen berikan nama "kelas"</br>
                2. Pilih menu Dataset untuk import data review yang akan digunakan atau untuk mengganti dataset baru</br>
                3. Lakukan text pre-processing data dengan memilih tombol "Text Pre-processing" pada halaman Dataset
                </br>
                4. Lakukan pembobotan fitur dengan memilih tombol "Information Gain" pada halaman Text Pre-processing</br>
                5. Lakukan pengujian klasifikasi analisis sentimen dengan algoritma SVM pada menu "Klasifikasi SVM"</br>
                6. Hasil akurasi & confusion matrix akan ditampilkan</br>
                7. Lakukan pengujian klasifikasi analisis sentimen dengan algoritma SVM kernel RBF pada menu "Klasifikasi SVM RBF"</br>
                8. Masukkan nilai paramter C dan gamma terlebih dahulu, setelah itu pilih "Process"</br>
                9. Hasil akurasi & confusion matrix akan ditampilkan</br>
                10. Lakukan pengujian klasifikasi analisis sentimen dengan algoritma SVM kernel RBF dan IG pada menu "Klasifikasi SVM RBF IG"</br>
                11. Masukkan nilai paramter C, gamma dan jumlah top k (rentang 1-4999 fitur) terlebih dahulu, setelah itu pilih "Process"</br>
                12. Hasil akurasi & confusion matrix akan ditampilkan</br>
            </div>
            </div>
          </div>
        </div>
      </div>
  </div>
    <!--===================================================-->
    <!--End page content-->

</div>
{% endblock %}

Sentimen_Movie/sentimen_hotel/sentimen_hotel/templates/administrator/sentimen.html
{% extends "layouts/administrator.html" %}
{% load static %}

{% block sentimen %}
active-sub
{% endblock %}

{% block title %}
Sentimen Analisis | Klasifikasi Analisis Sentimen Movie Review
{% endblock %}

{% block css %}
<!--DataTables [ OPTIONAL ]-->
<link href="{% static 'plugins/datatables/media/css/dataTables.bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/datatables/extensions/Responsive/css/responsive.dataTables.min.css' %}" rel="stylesheet">
<!--Animate.css [ OPTIONAL ]-->
<link href="{% static 'plugins/animate-css/animate.min.css' %}" rel="stylesheet">

  <link href="{% static "plugins/dropify/css/dropify.css" %}" type="text/css" rel="stylesheet" media="screen,projection">
{% endblock %}

{% block content %}
<div id="content-container">
    <div id="page-head">

<div class="pad-all text-center">
<h3>Dataset Movie Review</h3>
<p>IMPORT DATASET</p>
</div>
        </div>


    <!--Page content-->
    <!--===================================================-->
    <div id="page-content">
      <div class="panel">
					    <div class="panel-heading">
					        <h3 class="panel-title">Dataset Movie Review</h3>
					    </div>

					    <div class="panel-body">

					        <table id="demo-dt-basic" class="table table-striped table-bordered" cellspacing="0" width="100%">
					            <thead>
					                <tr>

					                    <th>Text</th>
					                    <th>Sentimen</th>
					                </tr>
					            </thead>
					            <tbody>
                        {% for x in dataset %}
                          <tr>
                              <td>{{x.0}}</td>
                              <td>{{x.1}}</td>
                          </tr>
                        {% endfor %}
					            </tbody>
					        </table>
					    </div>
					</div>


          <div class="panel">
    					    <div class="panel-heading">
    					        <h3 class="panel-title">Import Dataset</h3>
    					    </div>
    					    <div class="panel-body demo-nifty-btn">
                    <button data-target="#demo-lg-modal" data-toggle="modal" class="btn btn-lg btn-primary">Import</button>
                    </div>
  </div>


  <div class="panel">
          <div class="panel-heading">
              <h3 class="panel-title">Process</h3>
          </div>
          <div class="panel-body demo-nifty-btn">
            <a  class="btn btn-lg btn-primary" href="{% url 'administrator:hasil' %}">Text Pre-processing</a>
            </div>
</div>
    <!--===================================================-->
    <!--End page content-->

</div>

<div id="demo-lg-modal" class="modal fade" tabindex="-1">
      <div class="modal-dialog modal-lg animated bounceIn">
          <div class="modal-content">
            <form class="formValidate2" id="formValidate2" name="form_tambah" method="post" action="{% url 'administrator:sentimen' %}" enctype="multipart/form-data">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i></button>
                  <h4 class="modal-title" id="myLargeModalLabel">Import Dataset</h4>
              </div>
              <div class="modal-body">

                  {% csrf_token %}
                <div class="row section">
            <div class="col-sm-12">
                <p>Upload Dataset (Maximum file upload size 10MB).</p>
                <input type="file" name="data" class="dropify" data-show-remove="false" data-allowed-file-extensions="csv" data-max-file-size="10M" required />
                    </div>
            </div>


              </div>

              <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>

              </form>
          </div>
      </div>
  </div>
{% endblock %}

{% block js %}

 <!--DataTables [ OPTIONAL ]-->
 <script src="{% static 'plugins/datatables/media/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables/media/js/dataTables.bootstrap.js' %}"></script>
<script src="{% static 'plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js' %}"></script>


 <!--DataTables Sample [ SAMPLE ]-->
 <script src="{% static 'js/demo/tables-datatables.js' %}"></script>
 <!--Bootbox Modals [ OPTIONAL ]-->
<script src="{% static 'plugins/bootbox/bootbox.min.js' %}"></script>

<script type="text/javascript" src="{% static "plugins/dropify/js/dropify.js" %}"></script>


 <script>
$(document).ready(function(){
    $('.dropify').dropify();

      // Translated
      $('.dropify-fr').dropify({
          messages: {
              default: 'Glissez-déposez un fichier ici ou cliquez',
              replace: 'Glissez-déposez un fichier ou cliquez pour remplacer',
              remove:  'Supprimer',
              error:   'Désolé, le fichier trop volumineux'
          }
      });

      // Used events
      var drEvent = $('.dropify-event').dropify();
      drEvent.on('dropify.beforeClear', function(event, element){
          return confirm("Do you really want to delete \"" + element.filename + "\" ?");
      });

      drEvent.on('dropify.afterClear', function(event, element){
          alert('File deleted');
      });
        });
 </script>
{% endblock %}